name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Check if Dockerfile exists
        run: ls -l

      - name: Build Docker Image
        run: docker build -t my-dockerhub-username/bff-microservice .

      - name: Tag Docker Image
        run: docker tag my-dockerhub-username/bff-microservice my-dockerhub-username/bff-microservice:latest

      - name: Push Docker Image
        run: docker push my-dockerhub-username/bff-microservice:latest


      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
