name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug - List files
        run: ls -l

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bff-microservice .

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/bff-microservice ${{ secrets.DOCKER_USERNAME }}/bff-microservice:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bff-microservice:latest


      - name: Set up Kubernetes (KinD)
        uses: helm/kind-action@v1.8.0

      - name: Verify Kubernetes Cluster
        run: kubectl cluster-info

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f k8s/